disabled_rules: # rule identifiers to exclude from running
 - trailing_whitespace
 - force_cast
 - force_try
 - large_tuple
 - todo
 - valid_ibinspectable
 - implicit_getter
 
opt_in_rules: # some rules are only opt-in
 - array_init
 - closure_body_length
 - closure_end_indentation
 - closure_spacing
 - collection_alignment
 - contains_over_filter_count
 - contains_over_filter_is_empty
 - contains_over_first_not_nil
 - contains_over_range_nil_comparison
 - discouraged_object_literal
 - discouraged_optional_boolean
 - empty_collection_literal
 - empty_count
 - empty_string
 - enum_case_associated_values_count
 - fatal_error_message
 - file_name_no_space
 - first_where
 - flatmap_over_map_reduce
 - force_unwrapping
 - identical_operands
 - implicitly_unwrapped_optional
 - last_where
 - legacy_multiple
 - legacy_random
 - let_var_whitespace
 - literal_expression_end_indentation
 - multiline_function_chains
 - multiline_parameters
 - operator_usage_whitespace
 - prefer_self_type_over_type_of_self
 - private_action
 - private_outlet
 - reduce_into
 - redundant_nil_coalescing
 - redundant_type_annotation
 - sorted_first_last
 - sorted_imports
 - strict_fileprivate
 - switch_case_on_newline
 - toggle_bool
 - unneeded_parentheses_in_closure_argument
 - unused_import
 - vertical_parameter_alignment_on_call
 - vertical_whitespace_closing_braces
 - yoda_condition
 
excluded: # paths to ignore during linting. Takes precedence over `included`.
 - Carthage
 - Pods

function_body_length: 60
line_length: 400
type_body_length: 250
file_length: 450

function_parameter_count: 10
cyclomatic_complexity: 15

identifier_name:
  min_length: 2
  max_length: 50

type_name:
  min_length:
    warning: 2
  max_length:
    warning: 45
    error: 60

closure_body_length: 25

